name: "Check"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 4096
          build-mount-path: '/nix'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: cachix/install-nix-action@bec50b45a8bb06017c42af46702a3f502adcfa9e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: shuredotnix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix flake check
      - run: nix build .#desktop --fallback
        continue-on-error: true
        id: build

      - if: steps.build.outcome == 'failure'
        run: |
          echo "build failed, retrying..."
          sleep 30
          nix build .#desktop --fallback
